function t270_scroll(hash,offset,speed){var $root=$('html, body');var target="";if(speed===undefined){speed=500}
try{target=$(hash)}catch(event){console.log("Exception t270: "+event.message);return!0}
if(target.length===0){target=$('a[name="'+hash.substr(1)+'"]');if(target.length===0){return!0}}
$root.animate({scrollTop:target.offset().top-offset},speed,function(){if(history.pushState){history.pushState(null,null,hash)}else{window.location.hash=hash}});return!0}
function t651_initPopup(recid){if(window.$isMobile){if($('#rec'+recid+' .t651__phone').length==0){return}
t651_phone=$('#rec'+recid+' .t651__phone').text().replace(/\s+/g,'');$('#rec'+recid+' .t651__btn').click(function(){window.location.href="tel:"+t651_phone;$('.t651__btn_wrapper').removeClass('t651__btn_animate');$('.t651__btn-text').css('display','none')});return}
$('#rec'+recid).attr('data-animationappear','off');$('#rec'+recid).css('opacity','1');var el=$('#rec'+recid).find('.t651__popup'),analitics=el.attr('data-track-popup'),hook="TildaCallBackWidget"+recid,obj=$('#rec'+recid+' .t651__btn');obj.click(function(e){if(obj.hasClass("t651__btn_active")){t651_closePopup();return}
obj.addClass("t651__btn_active");t651_showPopup(recid);e.preventDefault();if(analitics>''){Tilda.sendEventToStatistics(analitics,hook)}})}
function t651_showPopup(recid){var el=$('#rec'+recid),popup=el.find('.t651__popup');$('.t651__btn_wrapper').removeClass('t651__btn_animate');$('.t651__btn-text').css('display','none');popup.css('display','block');setTimeout(function(){popup.addClass('t651__popup_show')},50);$(document).keydown(function(e){if(e.keyCode==27){t651_closePopup()}})}
function t651_closePopup(){$('.t651__btn').removeClass('t651__btn_active');$('.t651__popup').removeClass('t651__popup_show');setTimeout(function(){$('.t651__popup').not('.t651__popup_show').css('display','none')},300)}
function t651_sendPopupEventToStatistics(popupname){var virtPage='/tilda/popup/';var virtTitle='Popup: ';if(popupname.substring(0,7)=='#popup:'){popupname=popupname.substring(7)}
virtPage+=popupname;virtTitle+=popupname;if(window.Tilda&&typeof Tilda.sendEventToStatistics=='function'){Tilda.sendEventToStatistics(virtPage,virtTitle,'',0)}else{if(ga){if(window.mainTracker!='tilda'){ga('send',{'hitType':'pageview','page':virtPage,'title':virtTitle})}}
if(window.mainMetrika>''&&window[window.mainMetrika]){window[window.mainMetrika].hit(virtPage,{title:virtTitle,referer:window.location.href})}}}
function t678_onSuccess(t678_form){var t678_inputsWrapper=t678_form.find('.t-form__inputsbox');var t678_inputsHeight=t678_inputsWrapper.height();var t678_inputsOffset=t678_inputsWrapper.offset().top;var t678_inputsBottom=t678_inputsHeight+t678_inputsOffset;var t678_targetOffset=t678_form.find('.t-form__successbox').offset().top;if($(window).width()>960){var t678_target=t678_targetOffset-200}else{var t678_target=t678_targetOffset-100}
if(t678_targetOffset>$(window).scrollTop()||($(document).height()-t678_inputsBottom)<($(window).height()-100)){t678_inputsWrapper.addClass('t678__inputsbox_hidden');setTimeout(function(){if($(window).height()>$('.t-body').height()){$('.t-tildalabel').animate({opacity:0},50)}},300)}else{$('html, body').animate({scrollTop:t678_target},400);setTimeout(function(){t678_inputsWrapper.addClass('t678__inputsbox_hidden')},400)}
var successurl=t678_form.data('success-url');if(successurl&&successurl.length>0){setTimeout(function(){window.location.href=successurl},500)}}
function t702_initPopup(recid){$('#rec'+recid).attr('data-animationappear','off');$('#rec'+recid).css('opacity','1');var el=$('#rec'+recid).find('.t-popup'),hook=el.attr('data-tooltip-hook'),analitics=el.attr('data-track-popup');el.bind('scroll',t_throttle(function(){if(window.lazy==='y'||$('#allrecords').attr('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}}));if(hook!==''){$('.r').on('click','a[href="'+hook+'"]',function(e){t702_showPopup(recid);t702_resizePopup(recid);e.preventDefault();if(window.lazy==='y'||$('#allrecords').attr('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}
if(analitics>''){var virtTitle=hook;if(virtTitle.substring(0,7)=='#popup:'){virtTitle=virtTitle.substring(7)}
Tilda.sendEventToStatistics(analitics,virtTitle)}})}}
function t702_onSuccess(t702_form){var t702_inputsWrapper=t702_form.find('.t-form__inputsbox');var t702_inputsHeight=t702_inputsWrapper.height();var t702_inputsOffset=t702_inputsWrapper.offset().top;var t702_inputsBottom=t702_inputsHeight+t702_inputsOffset;var t702_targetOffset=t702_form.find('.t-form__successbox').offset().top;if($(window).width()>960){var t702_target=t702_targetOffset-200}else{var t702_target=t702_targetOffset-100}
if(t702_targetOffset>$(window).scrollTop()||($(document).height()-t702_inputsBottom)<($(window).height()-100)){t702_inputsWrapper.addClass('t702__inputsbox_hidden');setTimeout(function(){if($(window).height()>$('.t-body').height()){$('.t-tildalabel').animate({opacity:0},50)}},300)}else{$('html, body').animate({scrollTop:t702_target},400);setTimeout(function(){t702_inputsWrapper.addClass('t702__inputsbox_hidden')},400)}
var successurl=t702_form.data('success-url');if(successurl&&successurl.length>0){setTimeout(function(){window.location.href=successurl},500)}}
function t702_lockScroll(){var body=$("body");if(!body.hasClass('t-body_scroll-locked')){var bodyScrollTop=(typeof window.pageYOffset!=='undefined')?window.pageYOffset:(document.documentElement||document.body.parentNode||document.body).scrollTop;body.addClass('t-body_scroll-locked');body.css("top","-"+bodyScrollTop+"px");body.attr("data-popup-scrolltop",bodyScrollTop)}}
function t702_unlockScroll(){var body=$("body");if(body.hasClass('t-body_scroll-locked')){var bodyScrollTop=$("body").attr("data-popup-scrolltop");body.removeClass('t-body_scroll-locked');body.css("top","");body.removeAttr("data-popup-scrolltop")
window.scrollTo(0,bodyScrollTop)}}
function t702_showPopup(recid){var el=$('#rec'+recid),popup=el.find('.t-popup');popup.css('display','block');el.find('.t-range').trigger('popupOpened');if(window.lazy==='y'||$('#allrecords').attr('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}
setTimeout(function(){popup.find('.t-popup__container').addClass('t-popup__container-animated');popup.addClass('t-popup_show')},50);$('body').addClass('t-body_popupshowed t702__body_popupshowed');if(/iPhone|iPad|iPod/i.test(navigator.userAgent)&&!window.MSStream){setTimeout(function(){t702_lockScroll()},500)}
el.find('.t-popup').mousedown(function(e){var windowWidth=$(window).width();var maxScrollBarWidth=17;var windowWithoutScrollBar=windowWidth-maxScrollBarWidth;if(e.clientX>windowWithoutScrollBar){return}
if(e.target==this){t702_closePopup(recid)}});el.find('.t-popup__close').click(function(e){t702_closePopup(recid)});el.find('.t-submit[href*="#"]').click(function(e){if($('body').hasClass('t-body_scroll-locked')){$('body').removeClass('t-body_scroll-locked')}});el.find('a[href*="#"]').click(function(e){var url=$(this).attr('href');if(!url||url.substring(0,7)!='#price:'){t702_closePopup(recid);if(!url||url.substring(0,7)=='#popup:'){setTimeout(function(){$('body').addClass('t-body_popupshowed')},300)}}});$(document).keydown(function(e){if(e.keyCode==27){t702_closePopup(recid)}})}
function t702_closePopup(recid){$('body').removeClass('t-body_popupshowed t702__body_popupshowed');$('#rec'+recid+' .t-popup').removeClass('t-popup_show');if(/iPhone|iPad|iPod/i.test(navigator.userAgent)&&!window.MSStream){t702_unlockScroll()}
setTimeout(function(){$('.t-popup').not('.t-popup_show').css('display','none')},300)}
function t702_resizePopup(recid){var el=$("#rec"+recid),div=el.find(".t-popup__container").height(),win=$(window).height()-120,popup=el.find(".t-popup__container");if(div>win){popup.addClass('t-popup__container-static')}else{popup.removeClass('t-popup__container-static')}}
function t702_sendPopupEventToStatistics(popupname){var virtPage='/tilda/popup/';var virtTitle='Popup: ';if(popupname.substring(0,7)=='#popup:'){popupname=popupname.substring(7)}
virtPage+=popupname;virtTitle+=popupname;if(window.Tilda&&typeof Tilda.sendEventToStatistics=='function'){Tilda.sendEventToStatistics(virtPage,virtTitle,'',0)}else{if(ga){if(window.mainTracker!='tilda'){ga('send',{'hitType':'pageview','page':virtPage,'title':virtTitle})}}
if(window.mainMetrika>''&&window[window.mainMetrika]){window[window.mainMetrika].hit(virtPage,{title:virtTitle,referer:window.location.href})}}}
function t770_init(recid){var rec=$('#rec'+recid);var navElem=rec.find('.t770');var isFixed=(navElem.css('position')=='fixed');var redactorMode=navElem.hasClass('t770_redactor-mode');if(!redactorMode){t770_highlight();navElem.removeClass('t770__beforeready');if(isFixed){t770_checkAnchorLinks(recid)}
if(isFixed&&navElem.attr('data-bgopacity-two')){t770_changebgopacitymenu(recid);$(window).bind('scroll',t_throttle(function(){t770_changebgopacitymenu(recid)},200))}
if(isFixed&&navElem.attr('data-appearoffset')){navElem.removeClass('t770__beforeready');t770_appearMenu(recid);$(window).bind('scroll',t_throttle(function(){t770_appearMenu(recid)},200))}}
if(rec.find('.t770__imglogo').attr('data-img-width')){t770_setLogoPadding(recid)}
if(rec.find('.t770__mobile_burger').length){t770_createMobileMenu(recid)}
t770_setBg(recid);$(window).bind('resize',t_throttle(function(){t770_setBg(recid)},200))}
function t770_setLogoPadding(recid){if($(window).width()>980){var t770__menu=$('#rec'+recid+' .t770');var t770__logo=t770__menu.find('.t770__logowrapper');var t770__leftpart=t770__menu.find('.t770__leftwrapper');var t770__rightpart=t770__menu.find('.t770__rightwrapper');t770__leftpart.css("padding-right",t770__logo.width()/2+50);t770__rightpart.css("padding-left",t770__logo.width()/2+50)}}
function t770_highlight(){var url=window.location.href;var pathname=window.location.pathname;if(url.substr(url.length-1)=="/"){url=url.slice(0,-1)}
if(pathname.substr(pathname.length-1)=="/"){pathname=pathname.slice(0,-1)}
if(pathname.charAt(0)=="/"){pathname=pathname.slice(1)}
if(pathname==""){pathname="/"}
$(".t770__list_item a[href='"+url+"']").addClass("t-active");$(".t770__list_item a[href='"+url+"/']").addClass("t-active");$(".t770__list_item a[href='"+pathname+"']").addClass("t-active");$(".t770__list_item a[href='/"+pathname+"']").addClass("t-active");$(".t770__list_item a[href='"+pathname+"/']").addClass("t-active");$(".t770__list_item a[href='/"+pathname+"/']").addClass("t-active")}
function t770_checkAnchorLinks(recid){if($(window).width()>=960){var t770_navLinks=$("#rec"+recid+" .t770__desktoplist .t770__list_item a:not(.tooltipstered)[href*='#']");if(t770_navLinks.length>0){t770_catchScroll(t770_navLinks)}}}
function t770_catchScroll(t770_navLinks){var t770_clickedSectionId=null,t770_sections=new Array(),t770_sectionIdTonavigationLink=[],t770_interval=100,t770_lastCall,t770_timeoutId;t770_navLinks=$(t770_navLinks.get().reverse());t770_navLinks.each(function(){var t770_cursection=t770_getSectionByHref($(this));if(typeof t770_cursection.attr("id")!="undefined"){t770_sections.push(t770_cursection)}
t770_sectionIdTonavigationLink[t770_cursection.attr("id")]=$(this)});t770_updateSectionsOffsets(t770_sections);t770_sections.sort(function(a,b){return b.attr("data-offset-top")-a.attr("data-offset-top")});$(window).bind('resize',t_throttle(function(){t770_updateSectionsOffsets(t770_sections)},200));$('.t770').bind('displayChanged',function(){t770_updateSectionsOffsets(t770_sections)});setInterval(function(){t770_updateSectionsOffsets(t770_sections)},5000);t770_highlightNavLinks(t770_navLinks,t770_sections,t770_sectionIdTonavigationLink,t770_clickedSectionId);t770_navLinks.click(function(){var t770_clickedSection=t770_getSectionByHref($(this));if(!$(this).hasClass("tooltipstered")&&typeof t770_clickedSection.attr("id")!="undefined"){t770_navLinks.removeClass('t-active');$(this).addClass('t-active');t770_clickedSectionId=t770_getSectionByHref($(this)).attr("id")}});$(window).scroll(function(){var t770_now=new Date().getTime();if(t770_lastCall&&t770_now<(t770_lastCall+t770_interval)){clearTimeout(t770_timeoutId);t770_timeoutId=setTimeout(function(){t770_lastCall=t770_now;t770_clickedSectionId=t770_highlightNavLinks(t770_navLinks,t770_sections,t770_sectionIdTonavigationLink,t770_clickedSectionId)},t770_interval-(t770_now-t770_lastCall))}else{t770_lastCall=t770_now;t770_clickedSectionId=t770_highlightNavLinks(t770_navLinks,t770_sections,t770_sectionIdTonavigationLink,t770_clickedSectionId)}})}
function t770_updateSectionsOffsets(sections){$(sections).each(function(){var t770_curSection=$(this);t770_curSection.attr("data-offset-top",t770_curSection.offset().top)})}
function t770_getSectionByHref(curlink){var t770_curLinkValue=curlink.attr("href").replace(/\s+/g,'');if(t770_curLinkValue[0]=='/'){t770_curLinkValue=t770_curLinkValue.substring(1)}
if(curlink.is('[href*="#rec"]')){return $(".r[id='"+t770_curLinkValue.substring(1)+"']")}else{return $(".r[data-record-type='215']").has("a[name='"+t770_curLinkValue.substring(1)+"']")}}
function t770_highlightNavLinks(t770_navLinks,t770_sections,t770_sectionIdTonavigationLink,t770_clickedSectionId){var t770_scrollPosition=$(window).scrollTop(),t770_valueToReturn=t770_clickedSectionId;if(t770_sections.length!=0&&t770_clickedSectionId==null&&t770_sections[t770_sections.length-1].attr("data-offset-top")>(t770_scrollPosition+300)){t770_navLinks.removeClass('t-active');return null}
$(t770_sections).each(function(e){var t770_curSection=$(this),t770_sectionTop=t770_curSection.attr("data-offset-top"),t770_id=t770_curSection.attr('id'),t770_navLink=t770_sectionIdTonavigationLink[t770_id];if(((t770_scrollPosition+300)>=t770_sectionTop)||(t770_sections[0].attr("id")==t770_id&&t770_scrollPosition>=$(document).height()-$(window).height())){if(t770_clickedSectionId==null&&!t770_navLink.hasClass('t-active')){t770_navLinks.removeClass('t-active');t770_navLink.addClass('t-active');t770_valueToReturn=null}else{if(t770_clickedSectionId!=null&&t770_id==t770_clickedSectionId){t770_valueToReturn=null}}
return!1}});return t770_valueToReturn}
function t770_setPath(){}
function t770_setBg(recid){var window_width=$(window).width();if(window_width>980){$(".t770").each(function(){var el=$(this);if(el.attr('data-bgcolor-setbyscript')=="yes"){var bgcolor=el.attr("data-bgcolor-rgba");el.css("background-color",bgcolor)}})}else{$(".t770").each(function(){var el=$(this);var bgcolor=el.attr("data-bgcolor-hex");el.css("background-color",bgcolor);el.attr("data-bgcolor-setbyscript","yes")})}}
function t770_appearMenu(recid){var window_width=$(window).width();if(window_width>980){$(".t770").each(function(){var el=$(this);var appearoffset=el.attr("data-appearoffset");if(appearoffset!=""){if(appearoffset.indexOf('vh')>-1){appearoffset=Math.floor((window.innerHeight*(parseInt(appearoffset)/100)))}
appearoffset=parseInt(appearoffset,10);if($(window).scrollTop()>=appearoffset){if(el.css('visibility')=='hidden'){el.finish();el.css("top","-50px");el.css("visibility","visible");el.animate({"opacity":"1","top":"0px"},200,function(){})}}else{el.stop();el.css("visibility","hidden")}}})}}
function t770_changebgopacitymenu(recid){var window_width=$(window).width();if(window_width>980){$(".t770").each(function(){var el=$(this);var bgcolor=el.attr("data-bgcolor-rgba");var bgcolor_afterscroll=el.attr("data-bgcolor-rgba-afterscroll");var bgopacityone=el.attr("data-bgopacity");var bgopacitytwo=el.attr("data-bgopacity-two");var menushadow=el.attr("data-menushadow");if(menushadow=='100'){var menushadowvalue=menushadow}else{var menushadowvalue='0.'+menushadow}
if($(window).scrollTop()>20){el.css("background-color",bgcolor_afterscroll);if(bgopacitytwo=='0'||menushadow==' '){el.css("box-shadow","none")}else{el.css("box-shadow","0px 1px 3px rgba(0,0,0,"+menushadowvalue+")")}}else{el.css("background-color",bgcolor);if(bgopacityone=='0.0'||menushadow==' '){el.css("box-shadow","none")}else{el.css("box-shadow","0px 1px 3px rgba(0,0,0,"+menushadowvalue+")")}}})}}
function t770_createMobileMenu(recid){var window_width=$(window).width(),el=$("#rec"+recid),menu=el.find(".t770"),burger=el.find(".t770__mobile");burger.click(function(e){menu.fadeToggle(300);$(this).toggleClass("t770_opened")})
$(window).bind('resize',t_throttle(function(){window_width=$(window).width();if(window_width>980){menu.fadeIn(0)}},200))}